### ISSUE TITLE
Ongoing Failing Test Cases .. because of window

### ISSUE THREAD

**Issue by The1nstructor** [The1nstructor/fapinstructor#12]
[orgasm.test.js](https://github.com/The1nstructor/fapinstructor/blob/master/src/game/actions/orgasm/__tests__/orgasm.test.js) always seems to produce an error when trying to test it. (I had to fix the paths first)

I looked at performance.js what would probably solve that issue but I was not able to figure out how.

the last call is a try to `window.performance.now` which fails:

```js
 ● Test suite failed to run

    TypeError: Cannot read property 'now' of undefined
      
      at Object.<anonymous> (src/engine/loop.js:33:27)
      at Object.<anonymous> (src/game/index.js:4:13)
      at Object.<anonymous> (src/game/actions/orgasm/orgasm.js:11:13)
      at Object.<anonymous> (src/game/actions/orgasm/__tests__/orgasm.test.js:5:15)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by LenAnderson** [comment]
I believe nodejs does not have the global `window`?

Calling it as `performance.now()` instead and including a reference to the [Performance Timing API](https://nodejs.org/api/perf_hooks.html) for the tests might work because in the browser `window.performance.now()` and `performance.now()` are the same (unless something redefines `performance` in local scope).

Or maybe the testing library being used has some kind of "pretend this happens in a browser" mode...?

**Comment by The1nstructor** [comment]
whew. I don't have a clue 😞 

But the testEnv is not nodejs. I used jsdom what usually mocks a window ... but this window does not have preference.now(). Sadly

**Comment by LenAnderson** [comment]
Looks like jsom should have `performance.now()`

https://github.com/jsdom/jsdom/pull/2094

Perhaps the version being used here is outdated?
